config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :harvests, except: %i[index destroy]
  resources :offerings
  resources :locations
  resources :products, except: :destroy
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  resource :session, only: %i[new create destroy]
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/offering.rb
# frozen_string_literal: true

class Offering < ApplicationRecord
  belongs_to :location
  acts_as_tenant :organization

  has_many :offered_products, dependent: :destroy, inverse_of: :offering
  has_many :products, through: :offered_products

  accepts_nested_attributes_for :offered_products, allow_destroy: true, reject_if: :all_blank

  scope :open_now, lambda {
    where('opens_at <= ?', Time.zone.now)
      .where('closes_at >= ?', Time.zone.now)
  }

  validates :opens_at, :closes_at, presence: true
  validate :closes_after_opening?

  def open?(now)
    opens_at <= now && closes_at >= now
  end

  def before_opening?
    opens_at > Time.now
  end

  private

  def closes_after_opening?
    return unless closes_at < opens_at

    errors.add(:closes_at, 'Must be after opens_at')
  end
end

app/controllers/offerings_controller.rb
# frozen_string_literal: true

class OfferingsController < ApplicationController
  before_action :require_login
  before_action :set_offering, only: %i[ show edit update destroy ]

  # GET /offerings or /offerings.json
  def index
    @offerings = Offering.all
  end

  # GET /offerings/1 or /offerings/1.json
  def show; end

  # GET /offerings/new
  def new
    @offering = Offering.new
    @offering.offered_products.build
    authorize @offering
  end

  # GET /offerings/1/edit
  def edit; end

  # POST /offerings or /offerings.json
  def create
    @offering = Offering.new(offering_params)
    @offering.organization = current_organization
    authorize @offering

    respond_to do |format|
      if @offering.save
        format.html { redirect_to offering_url(@offering), notice: 'Offering was successfully created.' }
        format.json { render :show, status: :created, location: @offering }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offerings/1 or /offerings/1.json
  def update
    respond_to do |format|
      if @offering.update(offering_params)
        format.html { redirect_to offering_url(@offering), notice: 'Offering was successfully updated.' }
        format.json { render :show, status: :ok, location: @offering }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerings/1 or /offerings/1.json
  def destroy
    @offering.update_attribute!(:active, false)

    respond_to do |format|
      format.html { redirect_to offerings_url, notice: 'Offering was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_offering
    @offering = Offering.find(params[:id])
    authorize @offering
  end

  # Only allow a list of trusted parameters through.
  def offering_params
    params.require(:offering).permit(
      :opens_at, :closes_at, :harvest_at, :location_id,
      offered_products_attributes: %i[id product_id amount _destroy]
    )
  end
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/offerings/_form.html.erb
<%= form_with(
  model: offering,
  local: true,
  data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }
) do |form| %>
  <% if offering.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

      <ul>
        <% offering.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :opens_at, style: "display: block" %>
    <%= form.datetime_field :opens_at %>
  </div>

  <div>
    <%= form.label :closes_at, style: "display: block" %>
    <%= form.datetime_field :closes_at %>
  </div>

  <div>
    <%= form.label :harvest_at, style: "display: block" %>
    <%= form.date_field :harvest_at %>
  </div>

  <div>
    <%= form.label :location_id, style: "display: block" %>
    <%= form.collection_select(:location_id, Location.all, :id, :name) %>
  </div>

  <h3>Offered Products</h3>
  <template data-nested-form-target="template">
    <%= form.fields_for :offered_products, OfferedProduct.new(offering: offering), child_index: 'NEW_RECORD' do |offered_product_fields| %>
      <%= render "offered_product_fields", form: offered_product_fields %>
    <% end %>
  </template>

  <%= form.fields_for :offered_products do |offered_product_fields| %>
    <%= render "offered_product_fields", form: offered_product_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <div class="links">
    <%= button_tag 'Add Product', type: 'button', data: { action: 'nested-form#add' } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/offerings/_offered_product_fields.html.erb
<div class="nested-form-wrapper data-new-record="<%= form.object.new_record? %>>
  <div class="field">
    <%= form.label :product_id, "Product" %>
    <%= form.collection_select :product_id, Product.all, :id, :name, prompt: "Select a product" %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <%= button_tag 'Remove', type: 'button', data: { action: 'nested-form#remove' } %>
  <%= form.hidden_field :_destroy %>
</div>

app/views/offerings/_offering.html.erb
<div id="<%= dom_id offering %>">
  <p>
    <strong>Opens at:</strong>
    <%= offering.opens_at %>
  </p>

  <p>
    <strong>Closes at:</strong>
    <%= offering.closes_at %>
  </p>

  <p>
    <strong>Harvest at:</strong>
    <%= offering.harvest_at %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= offering.location_id %>
  </p>

  <p>
    <strong>Organization:</strong>
    <%= offering.organization_id %>
  </p>

</div>

app/views/offerings/edit.html.erb
<h1>Editing offering</h1>

<%= render "form", offering: @offering %>

<br>

<div>
  <%= link_to "Show this offering", @offering %> |
  <%= link_to "Back to offerings", offerings_path %>
</div>

app/views/offerings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Offerings</h1>

<div id="offerings">
  <% @offerings.each do |offering| %>
    <%= render offering %>
    <p>
      <%= link_to "Show this offering", offering %>
    </p>
  <% end %>
</div>

<%= link_to "New offering", new_offering_path %>

app/views/offerings/new.html.erb
<h1>New offering</h1>

<%= render "form", offering: @offering %>

<br>

<div>
  <%= link_to "Back to offerings", offerings_path %>
</div>

app/views/offerings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @offering %>

<div>
  <%= link_to "Edit this offering", edit_offering_path(@offering) %> |
  <%= link_to "Back to offerings", offerings_path %>

  <%= button_to "Destroy this offering", @offering, method: :delete %>
</div>