config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :harvests, except: %i[index destroy]
  resources :offerings
  resources :locations
  resources :products, except: :destroy
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  resource :session, only: %i[new create destroy]
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/harvest.rb
class Harvest < ApplicationRecord
  belongs_to :offering
  belongs_to :user
  has_many :harvested_products, dependent: :destroy, inverse_of: :harvest

  accepts_nested_attributes_for :harvested_products, allow_destroy: true, reject_if: :all_blank

  scope :current, -> { where(offering_id: Offering.open_now) }
end

app/controllers/harvests_controller.rb
# frozen_string_literal: true

class HarvestsController < ApplicationController
  before_action :require_login
  before_action :set_current_offering, only: %i[new create edit update]
  before_action :set_harvest, only: %i[show edit update]

  # GET /harvests/1 or /harvests/1.json
  def show; end

  # GET /harvests/new
  def new
    @harvest = Harvest.new
    @harvest.harvested_products.build
    authorize(@harvest)
  end

  # GET /harvests/1/edit
  def edit; end

  # POST /harvests or /harvests.json
  def create
    @harvest = Harvest.new(harvest_params)
    @harvest.user = current_user
    @harvest.offering = @current_offering
    authorize(@harvest)

    respond_to do |format|
      if @harvest.save
        format.html { redirect_to harvest_url(@harvest), notice: 'Harvest was successfully created.' }
        format.json { render :show, status: :created, location: @harvest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @harvest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /harvests/1 or /harvests/1.json
  def update
    respond_to do |format|
      if @harvest.update(harvest_params)
        format.html { redirect_to harvest_url(@harvest), notice: 'Harvest was successfully updated.' }
        format.json { render :show, status: :ok, location: @harvest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @harvest.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_harvest
    @harvest = Harvest.find(params[:id])
    authorize(@harvest)
  end

  def harvest_params
    params.require(:harvest).permit(harvested_products_attributes: %i[id offered_product_id amount _destroy])
  end

  def set_current_offering
    @current_offering = current_user.current_offering
  end
end

app/helpers/harvests_helper.rb
module HarvestsHelper
  def harvested_product(offered_product, current_user)
    return HarvestedProduct.new(offered_product_id: offered_product.id) if action_name == 'new'

    offered_product.harvested_products.from_user(current_user) ||
      HarvestedProduct.new(offered_product_id: offered_product.id)
  end
end

app/views/harvests/_form.html.erb
<%= form_with(model: harvest) do |form| %>
  <% if harvest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(harvest.errors.count, "error") %> prohibited this harvest from being saved:</h2>

      <ul>
        <% harvest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :harvested_products, style: "display: block" %>
    <% @current_offering.offered_products.each do |offered| %>
      <p><%= "#{offered.product_name}: #{offered.amount}" %></p>
      <%= form.fields_for :harvested_products, harvested_product(offered, current_user) do |harvested_fields| %>
        <%= harvested_fields.label :amount %>
        <%= harvested_fields.text_field :amount %>
        <%= harvested_fields.hidden_field :offered_product_id %>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/harvests/_harvest.html.erb
<div id="<%= dom_id harvest %>">
  <p>
    <strong>Offering:</strong>
    <%= harvest.offering_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= harvest.user_id %>
  </p>

  <%= harvest.harvested_products.count %>
  <% harvest.harvested_products.each do |harvested| %>
    <%= "#{harvested.product_name}: #{harvested.amount}" %>
  <% end %>
</div>

app/views/harvests/edit.html.erb
<h1>Editing harvest</h1>

<%= render "form", harvest: @harvest %>

<br>

<div>
  <%= link_to "Show this harvest", @harvest %> |
  <%= link_to "Back to harvests", harvests_path %>
</div>

app/views/harvests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Harvests</h1>

<div id="harvests">
  <% @harvests.each do |harvest| %>
    <%= render harvest %>
    <p>
      <%= link_to "Show this harvest", harvest %>
    </p>
  <% end %>
</div>

<%= link_to "New harvest", new_harvest_path %>

app/views/harvests/new.html.erb
<h1>New harvest</h1>

<%= render "form", harvest: @harvest %>

<br>

<div>
  <%= link_to "Back to harvests", harvests_path %>
</div>

app/views/harvests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @harvest %>

<div>
  <%= link_to "Edit this harvest", edit_harvest_path(@harvest) %> |
  <%= link_to "Back to harvests", harvests_path %>

  <%= button_to "Destroy this harvest", @harvest, method: :delete %>
</div>